### ISSUE TITLE
Git help

### ISSUE THREAD

**Issue by fanbyprinciple** [Aprisyta/coding_interview_questions#18]
Do you know how I an synchronise (pull) from your repo to mine. Right now you have arranged problems in folders I dont have the folder so all programs are going outside. I dont want to do a fresh fork.

**Comment by Aprisyta** [comment]
The term you are looking for is- syncing forks with the upstream project. Found below links. Should be useful.

[GitHub documentation on syncing forks with main repo](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)
[StackOverflow's answer](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Comment by fanbyprinciple** [comment]
to the rescue like a pro, Thanks
