### ISSUE TITLE
Arrange questions in folders.

### ISSUE THREAD

**Issue by Aprisyta** [Aprisyta/coding_interview_questions#4]
To be arranged topic wise? Or, according to the language? Probably, topic -> language?

**Comment by fanbyprinciple** [comment]
I guess topic wise if required. Because language is almost immaterial, I feel its more upto personal preferences.

**Comment by fanbyprinciple** [comment]
But I saw your format for comment as a preamble to question today, which mentions sources and all. I guess that's something  important. Also I putting a leetcode question number in front of my submission for quick ref I don't know if its necessary. 

And as an aside how do you even find the solution complexity.

Also leetcode does a good job of organising questions topic wise, can we leverage that.

**Comment by Aprisyta** [comment]
Yes, we can use leetcode's question indexing. I'll put question number too. Does make sense.

**Comment by Aprisyta** [comment]
This is done
